### ISSUE TITLE
Paint the second coat of base paint on walls and windows

### ISSUE THREAD

**Issue by mitar** [cloyne/hackerspace#1]
We put the first coat. We have to paint the second coat of base paint on walls and windows.

**Comment by lesloche** [comment]
Join me on Friday from 2.45ish to 5pm to start gathering all the stuffs in the middle of the room in order to paint the second coat! Yuhu, let's do this

**Comment by mitar** [comment]
3>

**Comment by nerdynucleon** [comment]
I'm here

**Comment by lesloche** [comment]
I'm finishing my tea and i'll be down in a few minutes, got late at the
food collective sorry :)
Le 30 janv. 2015 15:36, "Alexandre Chong" <notifications@github.com> a
écrit :

**Comment by mitar** [comment]
Oh, I was there and then there was nobody there so I went back up. :-( And even I meet you, @lesloche and it didn't look like any action. :-(

**Comment by lesloche** [comment]
You might want to go down a second time my dear Mitar, because SHIT HAPPENED

Oh, I was there and then there was nobody there so I went back up. :-( And
even I meet you, @lesloche <https://github.com/lesloche> and it didn't look
like any action. :-(

—
Reply to this email directly or view it on GitHub
<https://github.com/cloyne/hackerspace/issues/1#issuecomment-72296462>.

**Comment by mitar** [comment]
It looks sooo great! Amazing work! :-) Aaaa. :-)

**Comment by nerdynucleon** [comment]
2nd coat on! let's spend 30 min next week getting the last few spots.
